<!doctype html>
<html>
<head>
    <title>IcoMoon - SVG Icons</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="demo-files/demo.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
<header class="bgc1 clearfix">
<div class="mhl">
    <p>SVG Icons - Generated by <a href="https://icomoon.io/app">IcoMoon</a></p><p><strong>Notice</strong>: This demo (along with "symbol-defs.svg" and "svgxuse.js" files) should be <b>hosted on a web server</b> to work properly.</p>
</div>
</header>
    <div class="clearfix mhl ptl">
        <h1 class="mvm mtn fgc1">Grid Size: 16</h1>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-home"><use xlink:href="symbol-defs.svg#i-home"></use></svg><span class="name"> i-home</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-home3"><use xlink:href="symbol-defs.svg#i-home3"></use></svg><span class="name"> i-home3</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-play"><use xlink:href="symbol-defs.svg#i-play"></use></svg><span class="name"> i-play</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-cart"><use xlink:href="symbol-defs.svg#i-cart"></use></svg><span class="name"> i-cart</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-credit-card"><use xlink:href="symbol-defs.svg#i-credit-card"></use></svg><span class="name"> i-credit-card</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-phone"><use xlink:href="symbol-defs.svg#i-phone"></use></svg><span class="name"> i-phone</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-address-book"><use xlink:href="symbol-defs.svg#i-address-book"></use></svg><span class="name"> i-address-book</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-envelop"><use xlink:href="symbol-defs.svg#i-envelop"></use></svg><span class="name"> i-envelop</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-compass"><use xlink:href="symbol-defs.svg#i-compass"></use></svg><span class="name"> i-compass</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-history"><use xlink:href="symbol-defs.svg#i-history"></use></svg><span class="name"> i-history</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-clock"><use xlink:href="symbol-defs.svg#i-clock"></use></svg><span class="name"> i-clock</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-clock2"><use xlink:href="symbol-defs.svg#i-clock2"></use></svg><span class="name"> i-clock2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-calendar"><use xlink:href="symbol-defs.svg#i-calendar"></use></svg><span class="name"> i-calendar</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-display"><use xlink:href="symbol-defs.svg#i-display"></use></svg><span class="name"> i-display</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-laptop"><use xlink:href="symbol-defs.svg#i-laptop"></use></svg><span class="name"> i-laptop</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-mobile"><use xlink:href="symbol-defs.svg#i-mobile"></use></svg><span class="name"> i-mobile</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-mobile2"><use xlink:href="symbol-defs.svg#i-mobile2"></use></svg><span class="name"> i-mobile2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-tablet"><use xlink:href="symbol-defs.svg#i-tablet"></use></svg><span class="name"> i-tablet</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-undo"><use xlink:href="symbol-defs.svg#i-undo"></use></svg><span class="name"> i-undo</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-redo"><use xlink:href="symbol-defs.svg#i-redo"></use></svg><span class="name"> i-redo</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-undo2"><use xlink:href="symbol-defs.svg#i-undo2"></use></svg><span class="name"> i-undo2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-redo2"><use xlink:href="symbol-defs.svg#i-redo2"></use></svg><span class="name"> i-redo2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-bubble"><use xlink:href="symbol-defs.svg#i-bubble"></use></svg><span class="name"> i-bubble</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-bubbles"><use xlink:href="symbol-defs.svg#i-bubbles"></use></svg><span class="name"> i-bubbles</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-bubbles2"><use xlink:href="symbol-defs.svg#i-bubbles2"></use></svg><span class="name"> i-bubbles2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-bubbles4"><use xlink:href="symbol-defs.svg#i-bubbles4"></use></svg><span class="name"> i-bubbles4</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-spinner"><use xlink:href="symbol-defs.svg#i-spinner"></use></svg><span class="name"> i-spinner</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-spinner6"><use xlink:href="symbol-defs.svg#i-spinner6"></use></svg><span class="name"> i-spinner6</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-spinner8"><use xlink:href="symbol-defs.svg#i-spinner8"></use></svg><span class="name"> i-spinner8</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-spinner9"><use xlink:href="symbol-defs.svg#i-spinner9"></use></svg><span class="name"> i-spinner9</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-wrench"><use xlink:href="symbol-defs.svg#i-wrench"></use></svg><span class="name"> i-wrench</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-cog"><use xlink:href="symbol-defs.svg#i-cog"></use></svg><span class="name"> i-cog</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-cogs"><use xlink:href="symbol-defs.svg#i-cogs"></use></svg><span class="name"> i-cogs</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-leaf"><use xlink:href="symbol-defs.svg#i-leaf"></use></svg><span class="name"> i-leaf</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-truck"><use xlink:href="symbol-defs.svg#i-truck"></use></svg><span class="name"> i-truck</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-menu"><use xlink:href="symbol-defs.svg#i-menu"></use></svg><span class="name"> i-menu</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-menu2"><use xlink:href="symbol-defs.svg#i-menu2"></use></svg><span class="name"> i-menu2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-menu3"><use xlink:href="symbol-defs.svg#i-menu3"></use></svg><span class="name"> i-menu3</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-menu4"><use xlink:href="symbol-defs.svg#i-menu4"></use></svg><span class="name"> i-menu4</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-star-empty"><use xlink:href="symbol-defs.svg#i-star-empty"></use></svg><span class="name"> i-star-empty</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-star-half"><use xlink:href="symbol-defs.svg#i-star-half"></use></svg><span class="name"> i-star-half</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-star-full"><use xlink:href="symbol-defs.svg#i-star-full"></use></svg><span class="name"> i-star-full</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-point-up"><use xlink:href="symbol-defs.svg#i-point-up"></use></svg><span class="name"> i-point-up</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-point-right"><use xlink:href="symbol-defs.svg#i-point-right"></use></svg><span class="name"> i-point-right</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-point-down"><use xlink:href="symbol-defs.svg#i-point-down"></use></svg><span class="name"> i-point-down</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-point-left"><use xlink:href="symbol-defs.svg#i-point-left"></use></svg><span class="name"> i-point-left</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-cancel-circle"><use xlink:href="symbol-defs.svg#i-cancel-circle"></use></svg><span class="name"> i-cancel-circle</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-cross"><use xlink:href="symbol-defs.svg#i-cross"></use></svg><span class="name"> i-cross</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-checkmark"><use xlink:href="symbol-defs.svg#i-checkmark"></use></svg><span class="name"> i-checkmark</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-checkmark2"><use xlink:href="symbol-defs.svg#i-checkmark2"></use></svg><span class="name"> i-checkmark2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-up"><use xlink:href="symbol-defs.svg#i-arrow-up"></use></svg><span class="name"> i-arrow-up</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-right"><use xlink:href="symbol-defs.svg#i-arrow-right"></use></svg><span class="name"> i-arrow-right</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-down"><use xlink:href="symbol-defs.svg#i-arrow-down"></use></svg><span class="name"> i-arrow-down</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-left"><use xlink:href="symbol-defs.svg#i-arrow-left"></use></svg><span class="name"> i-arrow-left</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-up2"><use xlink:href="symbol-defs.svg#i-arrow-up2"></use></svg><span class="name"> i-arrow-up2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-right2"><use xlink:href="symbol-defs.svg#i-arrow-right2"></use></svg><span class="name"> i-arrow-right2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-down2"><use xlink:href="symbol-defs.svg#i-arrow-down2"></use></svg><span class="name"> i-arrow-down2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-arrow-left2"><use xlink:href="symbol-defs.svg#i-arrow-left2"></use></svg><span class="name"> i-arrow-left2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-circle-up"><use xlink:href="symbol-defs.svg#i-circle-up"></use></svg><span class="name"> i-circle-up</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-circle-right"><use xlink:href="symbol-defs.svg#i-circle-right"></use></svg><span class="name"> i-circle-right</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-circle-down"><use xlink:href="symbol-defs.svg#i-circle-down"></use></svg><span class="name"> i-circle-down</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-circle-left"><use xlink:href="symbol-defs.svg#i-circle-left"></use></svg><span class="name"> i-circle-left</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-checkbox-checked"><use xlink:href="symbol-defs.svg#i-checkbox-checked"></use></svg><span class="name"> i-checkbox-checked</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-checkbox-unchecked"><use xlink:href="symbol-defs.svg#i-checkbox-unchecked"></use></svg><span class="name"> i-checkbox-unchecked</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-mail2"><use xlink:href="symbol-defs.svg#i-mail2"></use></svg><span class="name"> i-mail2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-mail3"><use xlink:href="symbol-defs.svg#i-mail3"></use></svg><span class="name"> i-mail3</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-mail4"><use xlink:href="symbol-defs.svg#i-mail4"></use></svg><span class="name"> i-mail4</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-google"><use xlink:href="symbol-defs.svg#i-google"></use></svg><span class="name"> i-google</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-google2"><use xlink:href="symbol-defs.svg#i-google2"></use></svg><span class="name"> i-google2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-facebook"><use xlink:href="symbol-defs.svg#i-facebook"></use></svg><span class="name"> i-facebook</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-facebook2"><use xlink:href="symbol-defs.svg#i-facebook2"></use></svg><span class="name"> i-facebook2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-instagram"><use xlink:href="symbol-defs.svg#i-instagram"></use></svg><span class="name"> i-instagram</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-telegram"><use xlink:href="symbol-defs.svg#i-telegram"></use></svg><span class="name"> i-telegram</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-twitter"><use xlink:href="symbol-defs.svg#i-twitter"></use></svg><span class="name"> i-twitter</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-rss"><use xlink:href="symbol-defs.svg#i-rss"></use></svg><span class="name"> i-rss</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-rss2"><use xlink:href="symbol-defs.svg#i-rss2"></use></svg><span class="name"> i-rss2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-youtube"><use xlink:href="symbol-defs.svg#i-youtube"></use></svg><span class="name"> i-youtube</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-youtube2"><use xlink:href="symbol-defs.svg#i-youtube2"></use></svg><span class="name"> i-youtube2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-tumblr"><use xlink:href="symbol-defs.svg#i-tumblr"></use></svg><span class="name"> i-tumblr</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-tumblr2"><use xlink:href="symbol-defs.svg#i-tumblr2"></use></svg><span class="name"> i-tumblr2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-linkedin"><use xlink:href="symbol-defs.svg#i-linkedin"></use></svg><span class="name"> i-linkedin</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-linkedin2"><use xlink:href="symbol-defs.svg#i-linkedin2"></use></svg><span class="name"> i-linkedin2</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-pinterest"><use xlink:href="symbol-defs.svg#i-pinterest"></use></svg><span class="name"> i-pinterest</span>
            </div>
        </div>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon i-pinterest2"><use xlink:href="symbol-defs.svg#i-pinterest2"></use></svg><span class="name"> i-pinterest2</span>
            </div>
        </div>
  </div>
<script defer src="svgxuse.js"></script>
</body>
</html>
